CSV0 <- read.csv("merged_syntax_selected_both_tasks_normalized.csv", stringsAsFactors = FALSE)
CSV1 <- read.csv("merged_syntax_selected_graph_normalized.csv", stringsAsFactors = FALSE)
CSV2 <- read.csv("merged_syntax_selected_opinion_normalized.csv", stringsAsFactors = FALSE)

cor.test(CSV0$num_of_errors, CSV0$num_coord, method = "pearson")
cor.test(CSV0$num_of_errors, CSV0$num_noun_inf, method = "pearson")
cor.test(CSV0$num_of_errors, CSV0$num_poss, method = "pearson")
cor.test(CSV0$num_of_errors, CSV0$num_tu, method = "pearson")
cor.test(CSV0$num_of_errors, CSV0$num_part_noun, method = "pearson")
cor.test(CSV0$num_of_errors, CSV0$pos_sim_nei, method = "pearson")
cor.test(CSV0$num_of_errors, CSV0$lemma_sim_nei, method = "pearson")
cor.test(CSV0$num_of_errors, CSV0$pos_sim_all, method = "pearson")
cor.test(CSV0$num_of_errors, CSV0$lemma_sim_all, method = "pearson")


cor.test(CSV1$num_of_errors, CSV1$num_coord, method = "pearson")
cor.test(CSV1$num_of_errors, CSV1$num_poss, method = "pearson")
cor.test(CSV1$num_of_errors, CSV1$num_tu, method = "pearson")
cor.test(CSV1$num_of_errors, CSV1$num_noun_inf, method = "pearson")
cor.test(CSV1$num_of_errors, CSV1$num_part_noun, method = "pearson")
cor.test(CSV1$num_of_errors, CSV1$pos_sim_nei, method = "pearson")
cor.test(CSV1$num_of_errors, CSV1$lemma_sim_nei, method = "pearson")
cor.test(CSV1$num_of_errors, CSV1$pos_sim_all, method = "pearson")
cor.test(CSV1$num_of_errors, CSV1$lemma_sim_all, method = "pearson")


cor.test(CSV2$num_of_errors, CSV2$num_coord, method = "pearson",exact=FALSE)
cor.test(CSV2$num_of_errors, CSV2$num_poss, method = "pearson",exact=FALSE)
cor.test(CSV2$num_of_errors, CSV2$num_tu, method = "pearson",exact=FALSE)
cor.test(CSV2$num_of_errors, CSV2$num_part_noun, method = "pearson",exact=FALSE)
cor.test(CSV2$num_of_errors, CSV2$num_noun_inf, method = "pearson",exact=FALSE)
cor.test(CSV2$num_of_errors, CSV2$pos_sim_nei, method = "pearson",exact=FALSE)
cor.test(CSV2$num_of_errors, CSV2$lemma_sim_nei, method = "pearson",exact=FALSE)
cor.test(CSV2$num_of_errors, CSV2$pos_sim_all, method = "pearson",exact=FALSE)
cor.test(CSV2$num_of_errors, CSV2$lemma_sim_all, method = "pearson",exact=FALSE)

